### ISSUE TITLE
Landing Image

### ISSUE THREAD

**Issue by mhamilt** [chadmckell/chadmckell#1]
UNSOLICITED ADVICE!

Try changing the image tag on the landing page to: 

```html
<img src="images/membrane.jpg" width="100%">
```
That should hopefully get it to format nicely on different devices.

OR

You could also create a new class for the image. Something like this in a style sheet

``` css
.landing-image
{
    align: center
    max-width: 100%
}
```
and change the line to
```html
<img class="landing-image" src="images/membrane.jpg" >
```
